### ISSUE TITLE
Move this repo to `github.com/NixOS`

### ISSUE THREAD

**Issue by zowoq** [NixOS/aarch64-build-box#177]
It is confusing to have this repo in `nix-community` when doesn't have anything to do with us.

cc @zimbatm

**Comment by Mic92** [comment]
As long as this machine is also responsible for ofBorg, it probably will stay in this state.
I also agree that NixOS is than more appropriate.

**Comment by zimbatm** [comment]
Moved. This repo now belongs to the @NixOS/infra-build team

**Comment by zowoq** [comment]
Thanks!
