### ISSUE TITLE
SECURITY: Set a non-root user for the builds

### ISSUE THREAD

**Issue by Kreyren** [NixOS/aarch64-build-box#198]
For context: Using the root user wasn't acceptable for me to set up for [NiXium](https://github.com/NiXium-org/NiXium) so i am managing this issue through declaring a `builder` account, where this repo seems to just give everyone who needs to build for arm root access to their system.. that kinda seems well.. not great

Referencing https://github.com/NiXium-org/NiXium/blob/ec5a7e8b4f113de4cbd295221d6265e52454d629/src/nixos/modules/services/distributedBuilds/distributedBuilds.nix

Maybe similar management would work here as well? (I kinda need building of derivations for development of arm 64bit for OLIMEX Teres-I and arm 32bit for devices alike Nokia N900 and would like to address that backdoor prior to requesting access)

CC @mweinelt

**Comment by mweinelt** [comment]
The infra team has root access for the purpose of administrating this machine.

The endusers have dedicated accounts, which are part of the `trusted-users` group in nix. The implications of that access are explained in the [README](https://github.com/NixOS/aarch64-build-box#notes-on-security-and-safety).

I'm having a hard time understanding the issue you are pointing to.

**Comment by Kreyren** [comment]
My fault sorry, i got confused by an issue that NiXium manages and though that it affects things in this repo as well which was concluded to not be the case.
